// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_dvp4SCips-B1-RU1WvbuIhwLv2r1sI4',
    appId: '1:318065452005:web:893908d2d9478682aa050c',
    messagingSenderId: '318065452005',
    projectId: 'donvie-55125',
    authDomain: 'donvie-55125.firebaseapp.com',
    storageBucket: 'donvie-55125.firebasestorage.app',
    measurementId: 'G-84CBR5P07R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYCezk0rNgttxE1BBL-8q_ZJ1ycu_seHw',
    appId: '1:318065452005:android:11f60a83336fba41aa050c',
    messagingSenderId: '318065452005',
    projectId: 'donvie-55125',
    storageBucket: 'donvie-55125.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXxR-h3G-iwp2ehYCLibfrdEKyfWiwlZM',
    appId: '1:318065452005:ios:38df95eaad6c583eaa050c',
    messagingSenderId: '318065452005',
    projectId: 'donvie-55125',
    storageBucket: 'donvie-55125.firebasestorage.app',
    iosBundleId: 'com.example.healthEmergency',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXxR-h3G-iwp2ehYCLibfrdEKyfWiwlZM',
    appId: '1:318065452005:ios:38df95eaad6c583eaa050c',
    messagingSenderId: '318065452005',
    projectId: 'donvie-55125',
    storageBucket: 'donvie-55125.firebasestorage.app',
    iosBundleId: 'com.example.healthEmergency',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_dvp4SCips-B1-RU1WvbuIhwLv2r1sI4',
    appId: '1:318065452005:web:3fa1806056b05878aa050c',
    messagingSenderId: '318065452005',
    projectId: 'donvie-55125',
    authDomain: 'donvie-55125.firebaseapp.com',
    storageBucket: 'donvie-55125.firebasestorage.app',
    measurementId: 'G-66KBZH3CWX',
  );
}
